### ISSUE TITLE
studyProject项目中长连接测试问题

### ISSUE THREAD

**Issue by Anweizhen** [xcw-coder/muduo#1]
你好，请问studyProject
长连接测试的过程和短链接测试的过程是一样的吗？短链接测试没问题，但是长连接测试一直没有结果。

**Comment by Suzukaze-Aoba** [comment]
> 你好，请问studyProject
> 长连接测试的过程和短链接测试的过程是一样的吗？短链接测试没问题，但是长连接测试一直没有结果。

请去原作者的github问吧https://github.com/linyacool/WebServer
这个不要脸的家伙用别人的项目竟然把别人的MIT证书删掉了，改成自己的MIT证书
